### PR TITLE
CbTH: Binary/UBS support

### PR DESCRIPTION
**Pull request by woodruffw**
cc @jgarman @zacharyestep @askthedragon

### CODE REVIEW

**Comment by woodruffw** [comment]
> Nice clean changeset

Thanks! I'm going to add a model + calls to retrieve download URLs, after which I'd appreciate a review 😄

**Comment by woodruffw** [comment]
My understanding is that the "why" is because the `str` constructor can't handle `unicode` objects:

```python
>>> str(u'\xc2\xa9')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

I can steamroll past the initial encoding error with this hack:

```python
if PY2 and isinstance(self._info[attr], unicode):
    val = self._info[attr]
else:
    val = str(self._info[attr])
```

but that just causes the same error further down the stack:

```
File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
```

We can fix that by using `repr()`:

```python
if PY2 and isinstance(self._info[attr], unicode):
    val = repr(self._info[attr])
else:
    val = str(self._info[attr])
```

which leads to some slightly ugly (but workable) output:

```
            architecture: [u'amd64']
     available_file_size: 357376
              charset_id: 1200
                comments: None
            company_name: u'Microsoft Corporation'
               copyright: u'\xa9 Microsoft Corporation. All rights reserv...
          file_available: True
        file_description: u'Windows Command Processor'
               file_size: 357376
            file_version: u'6.3.9600.17415 (winblue_r4.141028-1500)'
           internal_name: u'cmd'
                 lang_id: 1033
                     md5: u'f5ae03de0ad60f5b17b82f2cd68402fe'
       original_filename: u'Cmd.Exe'
                 os_type: u'WINDOWS'
           private_build: None
     product_description: None
            product_name: u'Microsoft\xae Windows\xae Operating System'
         product_version: u'6.3.9600.17415'
                  sha256: u'6f88fb88ffb0f1d5465c2826e5b4f523598b1b8378377...
           special_build: None
               trademark: None
```

Thoughts? I think it's a little ugly to check for `PY2` and whether an attribute is a `unicode` instance, but I'm not sure Python 2 actually has a better way to convert arbitrary objects into strings.

**Comment by woodruffw** [comment]
Alternatively, we could probably do something like this to avoid the Python 2 check and only use `repr` when necessary:

```python
try:
  val = str(self._info[attr])
except UnicodeDecodeError:
  val = repr(self._info[attr])
```

**Comment by jgarman** [comment]
The secret sauce here is https://docs.djangoproject.com/en/2.1/_modules/django/utils/six/#python_2_unicode_compatible. This wraps `__str__` and `__unicode__` as needed between python 2 & 3, such that you just have to write a `__str__` object as if you were returning unicode, and the appropriate special methods are created on Python 2. See the wrapper around `cbapi.oldmodels.BaseModel` and `cbapi.models.NewBaseModel` for an example.

**Comment by jgarman** [comment]
Thanks @woodruffw !

**Pull request merged**
