### PR TITLE
FIX: Py3 - NameError: name 'long' is not defined

### PR DESCRIPTION
**Pull request by ruchirarya**
@bvasil-cb @avanbrunt-cb @llyon-cb Verify the modification, not sure if this would break something in Python 2 or not, but Python 3 has no data type "long". Feel free to modify accordingly.

### CODE REVIEW

**Comment by bvasil-cb** [comment]
Hi Ruchir, 
Thanks for the fix, we are a bit swamped this sprint, but we have a ticket in our backlog to verify it won't break python2. 
Thanks again for your contribution and support! 
Becca

**Comment by ruchirarya** [comment]
@avanbrunt-cb check when time permits.

**Comment by ruchirarya** [comment]
@bvasil-cb @avanbrunt-cb @llyon-cb @abowersox-cb

**Comment by abowersox-cb** [comment]
Simple enough once you understand how types can be reassigned. I approve.

**Comment by abowersox-cb** [comment]
I wasn't a reviewer, so I had to add myself before I could approve it :)

**Pull request merged**
