### PR TITLE
Account for sensor queue depth when scheduling jobs

### PR DESCRIPTION
**Pull request by davewagner2**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Tests have been added that prove the fix is effective or that the feature works.
- [X] New and existing tests pass locally with the changes.
- [X] Code follows the style guidelines of this project (PEP8, clean code).
- [X] Linter has passed locally and any fixes were made for failures.
- [X] A self-review of the code has been done.

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes (not tied to bugs/features)
- [X] Other (please describe): processing speed improvement

## Pull Request Description

Changes the sort for adding new jobs from next check-in time to: (total sensor queue length, next check-in time).

When processing a series of live response sessions against a very large number of sensors, I have found that large sensor binary and event queues tend to slow things down considerably. This small tweak to the sort logic in the job scheduler has improved processing considerably for jobs with thousands of sensors. It prioritizes sensors with the shortest job queues first for processing. This allows sensors with a backlog more time to drain without blocking the rest of the operation.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## How Has This Been Tested?

I have run this on long job submissions (8000+ sensors, running a series Live Response commands against all of them). It has improved the speed of processing the work.

### CODE REVIEW

**Comment by dly-cb** [comment]
@davewagner2 Hey Dave, are you able to git pull your branch and get it up to current date with master? We can easily just merge it afterwards!

**Comment by davewagner2** [comment]
@dly-cb I've caught my branch up with master. Should be good to go now. Thanks!

**Comment by dly-cb** [comment]
Hey @davewagner2, thanks so much for updating it! Were you able to use these changes for the new CB Response 7.1 changes?

**Comment by davewagner2** [comment]
@dly-cb yes, I've tested with the new 7.1 version of CB-Response. Several of our instances are now on 7.1.

**Comment by abowersox-cb** [comment]
Superseded by pull request #246.

**Pull request closed without merging**
