### PR TITLE
six.py replaced with 1.16 version and replaced readfp with read_file

### PR DESCRIPTION
**Pull request by averma-cb**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Tests have been added that prove the fix is effective or that the feature works.
- [ ] New and existing tests pass locally with the changes.
- [ ] Code follows the style guidelines of this project (PEP8, clean code).
- [ ] Linter has passed locally and any fixes were made for failures.
- [ ] A self-review of the code has been done.

## Pull request type

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes (not tied to bugs/features)
- [ ] Other (please describe):

## What is the ticket or issue number?

- Ticket Number: CRE-18007

- Issue Number: N/A

## Pull Request Description
Details in CRE

## Does this introduce a breaking change?
_Need Review_
- [ ] Yes
- [ ] No

## How Has This Been Tested?
Manually.

## Other information:

It does seem, python 3.6.9 does not work out, issue with deserializing protobufs 
3.7 worked out without any changes
3.12 fail to recognize cbapi.six.moves; Chaning six.py to latest from https://raw.githubusercontent.com/benjaminp/six/master/six.py helped the situation.

I did try to add back all #noqa comment back.
There was an EXPLICIT change that is now overridden, may need additional attention https://github.com/carbonblack/cbapi-python/commit/9ab1930ff0898b36514ad0712b7e337bed0358bb

### CODE REVIEW

**Comment by averma-cb** [comment]
Tagging. @kebringer-cb  @avanbrunt-cb  @emitreva-cb  
Internal ticket : https://bsg-jira.broadcom.net/browse/CRE-18007

**Comment by avanbrunt-cb** [comment]
How was this tested manually?

**Comment by averma-cb** [comment]
As suggested, did some manual testing on real test EDR. Working through issues.

**Comment by averma-cb** [comment]
Duh!
https://docs.python.org/3/whatsnew/3.12.html#:~:text=configparser.ConfigParser%20no%20longer%20has%20a%20readfp%20method.%20Use%20read_file()%20instead.

**Comment by averma-cb** [comment]
Quick Test Note:
```shell
zeek@zeek-ubuntu:~/test3.12$ source venv/bin/activate
(venv) zeek@zeek-ubuntu:~/test3.12$ cat ~/.carbonblack/credentials.response 
[default]
url = https://192.168.184.4
token = xxxxxxxxxx(masked)xxxxxxxxxx
ssl_verify = False

(venv) zeek@zeek-ubuntu:~/test3.12$ python3.12 --version
Python 3.12.0
(venv) zeek@zeek-ubuntu:~/test3.12$ python3.12 ~/cbapi-python/examples/response/feed_operations.py list | grep display_name
display_name        : Bit9 Software Reputation Service Trust
display_name        : Cb Reputation Threat
display_name        : National Vulnerability Database
display_name        : Carbon Black Advanced Threats Feed
display_name        : Carbon Black Early Access Indicators Feed
display_name        : Carbon Black Endpoint Visibility Feed
display_name        : Carbon Black Endpoint Suspicious Indicators Feed
display_name        : Carbon Black Abuse.ch
display_name        : Carbon Black AlienVault
display_name        : Carbon Black Banning Events
display_name        : Carbon Black Community Feed
display_name        : Carbon Black Detected EMET Events
display_name        : Carbon Black Endpoint Tamper Detection
display_name        : Carbon Black Facebook ThreatExchange
display_name        : Carbon Black Known IOCs Feed
display_name        : Carbon Black SANS
display_name        : Carbon Black TOR
display_name        : Cb Inspection
display_name        : Living Off The Land Drivers
display_name        : ThreatConnect Carbon Black Community
display_name        : ATT&CK Framework
(venv) zeek@zeek-ubuntu:~/test3.12$ 

```

**Review by csawan-vmware — APPROVED** [review]

**Review by avanbrunt-cb — APPROVED** [review]

**Pull request merged**
