### PR TITLE
Smaller and larger changes to base and response

### PR DESCRIPTION
**Pull request by rlmaers**
Hi,

Following are 17 commits in varying size that attempt to fix/improve things in base and response. Except for minor fixes here and there which are explained in the commit messages, the biggest changes are to cbapi.response.models.Process and related code. In summary, the latter changes attempt to address issues with data consistency and completeness. Following is a short description of what they entail.

- **cbapi.response.models.Process.__init__**: Clean up, deduplicate guid parsing and fix a bug where suppressed processes didn't have _full_init set to True because the superclass constructor was called too late and overwrote the previously set value.
- **cbapi.response.models.Process._parse**: Don't overwrite, but update previously stored information. Also, in case some fields are missing/have invalid values: attempt to deduce the correct value from the adjacent (siblings, children, parent) information objects. This is perhaps the largest addition in this pull request.
- **cbapi.response.models.Process.require_events**: Add functionality to specify segment id and min/max_last_update, such that it's possible to search events within a specified time span (i.e. segment=0 and min/max_last_update!=None) instead of just per segment. Since there can be more than the max default of 10 000 events, make sure to fetch until there are no more. Changes to cbapi.response.models.Process.netconns, etc. make sure that the changes to require_events shouldn't affect previous behaviour of these methods.
- **response.models.CbChildProcEvent.process**: Use the available data to provide as much as possible to the cbapi.response.models.Process constructor.
- **response.models.Process.children**: Use both childprocs and the children information object in the process summary as data source, as either can have missing data.

Please don't hesitate don't ask any questions.

### CODE REVIEW

**Comment by kebringer-cb** [comment]
Thanks for the commits.  We will review them for merging.

**Comment by rlmaers** [comment]
@avanbrunt-cb 

> Overall looks great!

Thanks!

>  I'd love to know some of the reasoning behind the changes in the response models.py.

Completely understandable. I'll do my best to fill the gaps in between the lines of code. 

### Background
In general, we're using Carbon Black Response in incident response to find and keep track of suspicious/malicious processes/activity. We initially used the webgui, but quickly found out that it was far too slow to process the amount of data that we'd like to work with on a daily basis. Secondly, using the event forwarder with a SIEM is either too slow or the data is too sparse for our needs. So we developed our own tooling on top of cbapi-python to scratch our own itch. It basically takes a list of servers and queries, fetches the results, does some parsing and stores them locally for further analysis and/or forwarding. 

### Description
An important feature of our tool is the ability to fetch the the process subtree, i.e. fetch the children of a process recursively. This has proved to be very useful for us, but the existing support for this in cbapi-python has been insufficient for the following reasons.

- Process.walk_children traverses only running processes based on the Process.children output.
- Process.children is either empty or a subset of all child processes (max 15 until recently).

The latter point is due to the fact that checked condition (`self._children_info is not None`) is never false, at least not if the process object was acquired from a process query. The ProcessQuery object instantiates Process objects with the process information from the result, which the Process constructor sends to the _parse method, which sets the __children_info to an empty list (since process summaries from results never contain a children object).

If require_events is called before _children_info, then _full_init is set to True and subsequent calls to _children_info returns an empty list. Otherwise _children_info will perform a refresh and fetch 15 child processes at most. While this might be sufficient in many cases, we need to trust that Carbon Black always returns all requested information unless specified otherwise.

### Solution
This a problem we discovered and worked around a few years ago. As the max_children flag was (and still is) undocumented, our solution was to fetch all childproc events and use those as the basis for the process tree traversal. It turned out that this wasn't a straight forward solution either, since there was no easy way to get all events across all segments for a process. We could either write the event fetching logic in our application or in the library, and we chose the latter since that's where it belongs. And that's the origin of the `require_all_events()` and `all_{property}()` methods that a colleague of mine upstreamed a few years ago.

Now, the reasoning behind the changes in this pull request remains the same, but the solution attempts be more complete and integrated into the existing framework. For instance, one of the issues with the previous solution is that the list of childproc events can be incomplete. Likewise, the same observation has been made with the children object from the process summary. So the current approach is to let Process.children to use both childproc events *and* the children object from the process summary.

While Process.children doesn't automatically return a list of all child processes by default, the sum of the changes in this pull request makes it at least possible. Furthermore, it does so with the existing (original) methods without breaking them and with backwards compatible enhancements where possible.

> One example being why we removed the functions `all_{property}()` and moved the functionality to the plain `{property}()` functions?

They duplicate a lot of code from the `require_event()` and `{property}()` methods and (as far as I know) we're the only users of these methods. It seemed better to integrate the functionality into the original methods if backwards compatibility could be retained, which I believe it is.

The other changes in the pull request are either somewhat related to the above or minor fixes/improvements I've done along the way. However, I'm afraid I'll write a book if I don't stop now, but I'm happy to answer any further questions you might have. :)

**Comment by rlmaers** [comment]
Hi! Any news on getting these changes merged?

**Comment by dly-cb** [comment]
Hey @rlmaers, I wanted to apologize for such a long and delayed response to your original PR. We wanted to say thank you for all of your time and work on this!! :)

Just a quick heads-up, CB Response 7.1 update was just released. We also made changes to CBAPI last week to match the updates. I'm currently reviewing the PR and going through this.  I'll get back to you asap on any questions I have!

**Comment by abowersox-cb** [comment]
Pull request has been divided into the base changes and the Response changes.  Base changes have been incorporated into pull request #245.  Response changes have been stashed on the branch "pr198-response-fixes" for later evaluation.

**Pull request closed without merging**
